"""Changed Film model

Revision ID: 36687fe4daf8
Revises: adf04038ec54
Create Date: 2024-07-21 14:02:58.717995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36687fe4daf8'
down_revision: Union[str, None] = 'adf04038ec54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('films', sa.Column('year', sa.String(), nullable=True))
    op.create_index(op.f('ix_films_slug'), 'films', ['slug'], unique=False)
    op.create_index(op.f('ix_films_year'), 'films', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_films_year'), table_name='films')
    op.drop_index(op.f('ix_films_slug'), table_name='films')
    op.drop_column('films', 'year')
    op.drop_column('films', 'slug')
    # ### end Alembic commands ###
