"""Add KP fields to Film model

Revision ID: a6612e41e273
Revises: 070d49667317
Create Date: 2024-07-24 13:18:25.257159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6612e41e273'
down_revision: Union[str, None] = '070d49667317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('lb_slug', sa.String(), nullable=True))
    op.add_column('films', sa.Column('kp_russian_title', sa.String(), nullable=True))
    op.add_column('films', sa.Column('kp_english_title', sa.String(), nullable=True))
    op.add_column('films', sa.Column('kp_director_name_rus', sa.String(), nullable=True))
    op.add_column('films', sa.Column('kp_year', sa.Integer(), nullable=True))
    op.drop_index('ix_films_slug', table_name='films')
    op.create_index(op.f('ix_films_lb_slug'), 'films', ['lb_slug'], unique=False)
    op.drop_column('films', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_films_lb_slug'), table_name='films')
    op.create_index('ix_films_slug', 'films', ['slug'], unique=False)
    op.drop_column('films', 'kp_year')
    op.drop_column('films', 'kp_director_name_rus')
    op.drop_column('films', 'kp_english_title')
    op.drop_column('films', 'kp_russian_title')
    op.drop_column('films', 'lb_slug')
    # ### end Alembic commands ###
