"""Initial migration

Revision ID: dab677406255
Revises: 
Create Date: 2024-07-21 15:03:38.684087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab677406255'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lb_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_films_id'), 'films', ['id'], unique=False)
    op.create_index(op.f('ix_films_lb_id'), 'films', ['lb_id'], unique=False)
    op.create_index(op.f('ix_films_slug'), 'films', ['slug'], unique=False)
    op.create_index(op.f('ix_films_username'), 'films', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_films_username'), table_name='films')
    op.drop_index(op.f('ix_films_slug'), table_name='films')
    op.drop_index(op.f('ix_films_lb_id'), table_name='films')
    op.drop_index(op.f('ix_films_id'), table_name='films')
    op.drop_table('films')
    # ### end Alembic commands ###
