"""Initial migration

Revision ID: db225ccbac78
Revises: 
Create Date: 2024-07-21 12:04:24.121790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db225ccbac78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_films_id', table_name='films')
    op.drop_index('ix_films_lb_id', table_name='films')
    op.drop_index('ix_films_title', table_name='films')
    op.drop_index('ix_films_username', table_name='films')
    op.drop_table('films')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('lb_id', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_films_username', 'films', ['username'], unique=False)
    op.create_index('ix_films_title', 'films', ['title'], unique=False)
    op.create_index('ix_films_lb_id', 'films', ['lb_id'], unique=False)
    op.create_index('ix_films_id', 'films', ['id'], unique=False)
    # ### end Alembic commands ###
